server:
  port: 8008
spring:
  datasource:
    url: jdbc:mysql://47.94.136.121:3306/taskplatform?characterEncoding=utf8&useSSL=false
    username: tasker
    password: sd1358582642
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 200
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: true
    # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
    max-pool-prepared-statement-per-connection-size: 50
  redis:
    port: 6000
    host: 47.94.136.121
    timeout: 6000ms

  thymeleaf:
    # 模板的模式
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false

#  mvc:
#    static-path-pattern=/static/**:

mybatis-plus:
  #  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  #开启驼峰命名转化
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #开启别名
  type-aliases-package: com.sd.task.pojo
#  type-handlers-package: com.sd.task.mapper
pagehelper:
  #页参数合理化
  reasonable: true
  #启用了分页,并且先执行了count后面的查询也拼接了limit
  helper-dialect: mysql
  #如果POJO或者Map中发现了countSql属性，就会作为count参数使用
  params: count=countSql
  support-methods-arguments: true
